services:
  - type: worker
    name: gxp-uploader
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: MQTT_BROKER
        sync: false
      - key: MQTT_PORT
        value: "8883"
      - key: MQTT_USER
        sync: false
      - key: MQTT_PASS
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SUPABASE_BUCKET
        value: petri-images
